### PR TITLE
Fix compilation error with gcc8.3

### PR DESCRIPTION
**Pull request by npaster**
Everything compile on debian 9 with gcc8.3 now

### CODE REVIEW

**Comment by datafl4sh** [comment]
Hello Nicolas,
This correction shouldn't be needed, gcc 8.3 should compile this code without problems since the syntax I used is legal C++20 (actually recently I am developing precisely with gcc8.3).
Maybe the actual problem is that C++20 is not enabled for those targets; I prepare a branch with the correct modifications so you can test later.

**Comment by npaster** [comment]
Hello Matteo,

This syntax is legal but I have a conflict at the compilation time with copy constructor.

Maybe the problem comes from that we use c++17 (and not c++20) and (I am on Debian 9)

Nicolas
